name: ci-cd

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - '*'

  workflow_dispatch:

jobs:
  ci-cd:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install requirements needed to run unit-tests.
      # As requirements.txt contains a link to a private git repository
      # we need to setup an ssh key to be able to fetch and install it
      - name: running unit-tests
        run: |
          sudo pip3 install .

      # Run unit tests
      - name: Run simulation unit-tests
        run: |
          mkdir test-dir
          cd test-dir
          cmake ../test
          make
          ctest -V
