name: unit-tests

on:
  push:
    branches:
      - '*'
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - '*'

  workflow_dispatch:

jobs:

  unit-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install requirements
        run: sudo pip3 install .

      - name: run unit-tests
        run: |
          mkdir test-dir
          cd test-dir
          cmake ../test
          git config --global init.defaultBranch master
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          make
          ctest -V
